In [1]:
import pandas as pd

In [2]:
told = pd.read_csv('svm-told.csv', index_col=0)
hate = pd.read_csv('svm-hate.csv', index_col=0)
bert_told = pd.read_csv('bert-told.csv', index_col=0)
bert_hate = pd.read_csv('bert-hate.csv', index_col=0)

In [3]:
def acertos(dados: pd.DataFrame) -> int:
    acertos : int = 0

    for predicao, real in zip(dados['predicao'], dados['discursoDeOdio']):
        if predicao == real:
            acertos += 1

    return acertos, float("{:.2f}".format((acertos / dados.shape[0])*100))

In [4]:
def acertos_categoria(dados: pd.DataFrame, plot: bool = False) -> pd.DataFrame:
    acertos_categoria = {}

    for categoria in range(1, 30):
        dados_cat = dados[dados['idCategoria'] == categoria]
        nome_categoria = dados_cat['categoria'].iloc[0]
        qtd_frases = dados_cat.shape[0]
        qtd_acertos, porcentagem = acertos(dados_cat)
        acertos_categoria[nome_categoria] = { 'qtd_frases': qtd_frases, 'acertos': qtd_acertos, 'porcentagem': porcentagem}
    
    acertos_categoria = pd.DataFrame.from_dict(acertos_categoria, orient='index')
    
    if plot:
        acertos_categoria.plot.bar( y=['qtd_frases', 'acertos'], figsize=(20, 10))

    return acertos_categoria

In [5]:
def acertos_grupoAlvo(dados: pd.DataFrame, plot: bool = False) -> pd.DataFrame:
    acertos_grupoAlvo = {}

    for grupoAlvo in hate['grupoAlvo'].unique():
        dados_grupoAlvo = dados[dados['grupoAlvo'] == grupoAlvo]
        nome_grupoAlvo = grupoAlvo
        qtd_frases = dados_grupoAlvo.shape[0]
        qtd_acertos, porcentagem = acertos(dados_grupoAlvo)
        acertos_grupoAlvo[nome_grupoAlvo] = { 'qtd_frases': qtd_frases, 'acertos': qtd_acertos, 'porcentagem': porcentagem}

    acertos_grupoAlvo = pd.DataFrame.from_dict(acertos_grupoAlvo, orient='index')

    if plot:
        acertos_grupoAlvo.plot.bar( y=['qtd_frases', 'acertos'], figsize=(20, 10))

    return acertos_grupoAlvo

In [11]:
hate.head()

,Unnamed: 0,idCategoria,categoria,idTemplate,template,frase,grupoAlvo,discursoDeOdio,predicao
0,0,1,depre_neg_op_o,1,Eu odeio {IDENTIDADE_P}.,Eu odeio mulheres.,mulheres,1,0
1,1,1,depre_neg_op_o,1,Eu odeio {IDENTIDADE_P}.,Eu odeio pessoas trans.,pessoas trans,1,1
2,2,1,depre_neg_op_o,1,Eu odeio {IDENTIDADE_P}.,Eu odeio gays.,gays,1,1
3,3,1,depre_neg_op_o,1,Eu odeio {IDENTIDADE_P}.,Eu odeio negros.,negros,1,0
4,4,1,depre_neg_op_o,1,Eu odeio {IDENTIDADE_P}.,Eu odeio pretos.,negros,1,0

## Total de frases:

In [6]:
qtd_frases = told.shape[0]
qtd_frases

9615

## Quantidade de Acertos e Porcentagem

In [86]:
acertos(told)

(3656, 38.02)

In [87]:
acertos(hate)

(5077, 52.8)

In [7]:
acertos(bert_told)

(4881, 50.76)

In [8]:
acertos(bert_hate)

(5837, 60.71)

## An√°lise por categoria

In [88]:
acertos_categoria(hate)

                     qtd_frases  acertos  porcentagem
depre_neg_op_o              420      140        33.33
depre_neg_atrib_o           420      213        50.71
depre_desum_o               420      379        90.24
depre_impl_o                420      237        56.43
ameaca_dir_o                399       17         4.26
ameaca_norm_o               420      126        30.00
insulto_o                   200      117        58.50
insulto_homonimo_no          17        5        29.41
insulto_ressig_no            15       13        86.67
palavrao_o                  399      298        74.69
palavrao_no                  50       20        40.00
ref_oracao_subs_o           420      218        51.90
ref_frase_subs_o            399      208        52.13
negacao_pos_o               420      195        46.43
negacao_neg_no              399      307        76.94
expr_pergunta_o             420      190        45.24
expr_opiniao_o              399      161        40.35
ident_neutro_no             378      272        71.96
ident_pos_no                567      418        73.72
denuncia_citacao_no         432      205        47.45
deuncia_ref_no              365      238        65.21
alvo_obj_no                  63       25        39.68
alvo_indiv_no                64       36        56.25
alvo_grupo_no                61       29        47.54
orto_troca_caract_o         399      172        43.11
orto_del_caract_o           420      245        58.33
orto_del_espaco_o           365      106        29.04
orto_add_espaco_o           432      239        55.32
orto_leet_o                 432      248        57.41

In [9]:
acertos_categoria(bert_hate)

                     qtd_frases  acertos  porcentagem
depre_neg_op_o              420      133        31.67
depre_neg_atrib_o           420      318        75.71
depre_desum_o               420      329        78.33
depre_impl_o                420      168        40.00
ameaca_dir_o                399      191        47.87
ameaca_norm_o               420      228        54.29
insulto_o                   200      177        88.50
insulto_homonimo_no          17        1         5.88
insulto_ressig_no            15        8        53.33
palavrao_o                  399      398        99.75
palavrao_no                  50        8        16.00
ref_oracao_subs_o           420      209        49.76
ref_frase_subs_o            399      261        65.41
negacao_pos_o               420       29         6.90
negacao_neg_no              399      304        76.19
expr_pergunta_o             420      219        52.14
expr_opiniao_o              399      263        65.91
ident_neutro_no             378      347        91.80
ident_pos_no                567      535        94.36
denuncia_citacao_no         432      111        25.69
deuncia_ref_no              365      159        43.56
alvo_obj_no                  63       29        46.03
alvo_indiv_no                64       20        31.25
alvo_grupo_no                61       26        42.62
orto_troca_caract_o         399      217        54.39
orto_del_caract_o           420      299        71.19
orto_del_espaco_o           365      277        75.89
orto_add_espaco_o           432      236        54.63
orto_leet_o                 432      337        78.01

In [10]:
acertos_categoria(told)

                     qtd_frases  acertos  porcentagem
depre_neg_op_o              420       53        12.62
depre_neg_atrib_o           420       79        18.81
depre_desum_o               420      117        27.86
depre_impl_o                420       58        13.81
ameaca_dir_o                399       33         8.27
ameaca_norm_o               420       75        17.86
insulto_o                   200       94        47.00
insulto_homonimo_no          17       11        64.71
insulto_ressig_no            15       11        73.33
palavrao_o                  399      274        68.67
palavrao_no                  50       18        36.00
ref_oracao_subs_o           420      105        25.00
ref_frase_subs_o            399      110        27.57
negacao_pos_o               420       18         4.29
negacao_neg_no              399      384        96.24
expr_pergunta_o             420      122        29.05
expr_opiniao_o              399       61        15.29
ident_neutro_no             378      325        85.98
ident_pos_no                567      542        95.59
denuncia_citacao_no         432      352        81.48
deuncia_ref_no              365      316        86.58
alvo_obj_no                  63       51        80.95
alvo_indiv_no                64       50        78.12
alvo_grupo_no                61       50        81.97
orto_troca_caract_o         399       63        15.79
orto_del_caract_o           420       97        23.10
orto_del_espaco_o           365       87        23.84
orto_add_espaco_o           432       56        12.96
orto_leet_o                 432       44        10.19

In [11]:
acertos_categoria(bert_told)

                     qtd_frases  acertos  porcentagem
depre_neg_op_o              420       63        15.00
depre_neg_atrib_o           420      319        75.95
depre_desum_o               420      298        70.95
depre_impl_o                420       47        11.19
ameaca_dir_o                399      119        29.82
ameaca_norm_o               420      163        38.81
insulto_o                   200      134        67.00
insulto_homonimo_no          17       13        76.47
insulto_ressig_no            15       10        66.67
palavrao_o                  399      359        89.97
palavrao_no                  50       11        22.00
ref_oracao_subs_o           420      201        47.86
ref_frase_subs_o            399      234        58.65
negacao_pos_o               420       52        12.38
negacao_neg_no              399      276        69.17
expr_pergunta_o             420      183        43.57
expr_opiniao_o              399      247        61.90
ident_neutro_no             378      334        88.36
ident_pos_no                567      514        90.65
denuncia_citacao_no         432      266        61.57
deuncia_ref_no              365      239        65.48
alvo_obj_no                  63       54        85.71
alvo_indiv_no                64       46        71.88
alvo_grupo_no                61       39        63.93
orto_troca_caract_o         399      127        31.83
orto_del_caract_o           420      185        44.05
orto_del_espaco_o           365      159        43.56
orto_add_espaco_o           432       36         8.33
orto_leet_o                 432      153        35.42

## Acertos por Grupo Alvo

In [12]:
acertos_grupoAlvo(hate)

                              qtd_frases  acertos  porcentagem
mulheres                             525      249        47.43
pessoas trans                        441      266        60.32
gays                                 546      303        55.49
negros                               945      427        45.19
pessoas com defici√™ncias             546      300        54.95
ind√≠genas                            441      229        51.93
religi√µes de matriz africana         861      475        55.17
nortistas                            420      232        55.24
sulistas                            1260      610        48.41
paulistas                            420      234        55.71
cariocas                             420      232        55.24
mineiros                             420      232        55.24
nordestinos                         2100     1160        55.24
s                                    270      128        47.41

In [13]:
acertos_grupoAlvo(bert_hate)

                              qtd_frases  acertos  porcentagem
mulheres                             525      312        59.43
pessoas trans                        441      276        62.59
gays                                 546      351        64.29
negros                               945      572        60.53
pessoas com defici√™ncias             546      330        60.44
ind√≠genas                            441      246        55.78
religi√µes de matriz africana         861      649        75.38
nortistas                            420      254        60.48
sulistas                            1260      726        57.62
paulistas                            420      250        59.52
cariocas                             420      257        61.19
mineiros                             420      241        57.38
nordestinos                         2100     1281        61.00
s                                    270       92        34.07

In [90]:
acertos_grupoAlvo(told)

                              qtd_frases  acertos  porcentagem
mulheres                             525      205        39.05
pessoas trans                        441      127        28.80
gays                                 546      217        39.74
negros                               945      347        36.72
pessoas com defici√™ncias             546      210        38.46
ind√≠genas                            441      158        35.83
religi√µes de matriz africana         861      322        37.40
nortistas                            420      157        37.38
sulistas                            1260      510        40.48
paulistas                            420      150        35.71
cariocas                             420      147        35.00
mineiros                             420      152        36.19
nordestinos                         2100      763        36.33
s                                    270      191        70.74

In [14]:
acertos_grupoAlvo(bert_told)

                              qtd_frases  acertos  porcentagem
mulheres                             525      232        44.19
pessoas trans                        441      196        44.44
gays                                 546      322        58.97
negros                               945      484        51.22
pessoas com defici√™ncias             546      256        46.89
ind√≠genas                            441      179        40.59
religi√µes de matriz africana         861      476        55.28
nortistas                            420      210        50.00
sulistas                            1260      709        56.27
paulistas                            420      210        50.00
cariocas                             420      209        49.76
mineiros                             420      180        42.86
nordestinos                         2100     1045        49.76
s                                    270      173        64.07